[package]
name = "rush"
version = "1.0.0"
edition = "2024"

[dependencies]
ansi_term = "0.12.1"
chrono = "0.4.41"
colored = "3.0.0"
rustyline = "14.0.0"
dirs = "6.0.0"
terminal_size = "0.4.2"
whoami = "1.6.0"
